name: Create Pull Request for Feature Branch

on:
  push:
    branches:
      - feature/*

jobs:
  create-pull-request:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Debug GitHub Context
        run: |
          echo "GITHUB_REF: $GITHUB_REF"
          echo "github.ref: ${{ github.ref }}"
          echo "github.ref_name: ${{ github.ref_name }}"
          echo "GITHUB_HEAD_REF: $GITHUB_HEAD_REF"
          echo "GITHUB_BASE_REF: $GITHUB_BASE_REF"

      - name: Determine Base Branch
        id: determine-base
        run: |
          BRANCH_NAME="${GITHUB_REF#refs/heads/}"
          FEATURE_NAME="${BRANCH_NAME#feature/}"
          BASE_BRANCH="epic/${FEATURE_NAME%%-*}"
          echo "BRANCH_NAME=${BRANCH_NAME}"
          echo "FEATURE_NAME=${FEATURE_NAME}"
          echo "BASE_BRANCH=${BASE_BRANCH}"
          echo "base_branch=${BASE_BRANCH}" >> $GITHUB_ENV

      - name: Create Pull Request
        uses: actions/github-script@v6
        with:
          script: |
            await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `자동 생성 PR - ${context.ref.replace('refs/heads/', '')}`,
              head: context.ref.replace('refs/heads/', ''),
              base: process.env.base_branch,
              body: '이 PR은 자동으로 생성되었습니다.'
            })
